FIRST_PRI_ENTS = ('GPE', 'ORG', 'NORP', 'PERSON')
SECOND_PRI_ENTS = ('WORK_OF_ART', 'LAW', 'FAC', 'LOC', 'PRODUCT', 'LANGUAGE')
THIRD_PRI_ENTS = ('PROPN', 'NOUN')

FIRST_NU_ENTS = ('CARDINAL', 'PERCENT', 'MONEY', 'QUANTITY', 'DATE')
SECOND_NU_ENTS = ('ORDINAL', 'TIME')
THIRD_NU_ENTS = ('NUMERAL')
